<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Service::insert([
            [
                "category_id" => 2,
                "label_id" => 1,
                "name" => "1 Song",
                "image" => "service-images/1.jpg",
                "price" => 150,
                "discounted_price" => null,
                "service_type" => "one_time",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mixing Services, Single Deal",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 2,
                "label_id" => 1,
                "name" => "1 Song + Dolby Atmos",
                "image" => "service-images/2.jpg",
                "price" => 299,
                "discounted_price" => null,
                "service_type" => "one_time",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mixing Services, Single Deal",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 2,
                "label_id" => 1,
                "name" => "8 Songs",
                "image" => "service-images/3.jpg",
                "price" => 1199,
                "discounted_price" => 999,
                "service_type" => "one_time",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mixing Services, Single Deal",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 2,
                "label_id" => 1,
                "name" => "8 Songs + Dolby Atmos",
                "image" => "service-images/4.jpg",
                "price" => 2399,
                "discounted_price" => 1999,
                "service_type" => "one_time",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mixing Services, Single Deal",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 2,
                "label_id" => 1,
                "name" => "5 Songs",
                "image" => "service-images/5.jpg",
                "price" => 599,
                "discounted_price" => null,
                "service_type" => "subscription",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mixing Services, Monthly Package",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 2,
                "label_id" => 1,
                "name" => "10 Songs",
                "image" => "service-images/6.jpg",
                "price" => 1200,
                "discounted_price" => null,
                "service_type" => "subscription",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mixing Services, Monthly Package",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 3,
                "label_id" => 1,
                "name" => "1 Song",
                "image" => "service-images/7.jpg",
                "price" => 100,
                "discounted_price" => null,
                "service_type" => "one_time",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mastering Services, Single Deal",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 3,
                "label_id" => 1,
                "name" => "1 Song + Dolby Atmos",
                "image" => "service-images/8.jpg",
                "price" => 200,
                "discounted_price" => null,
                "service_type" => "one_time",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mastering Services, Single Deal",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 3,
                "label_id" => 1,
                "name" => "8 Songs",
                "image" => "service-images/9.jpg",
                "price" => 1000,
                "discounted_price" => 800,
                "service_type" => "one_time",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mastering Services, Single Deal",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 3,
                "label_id" => 1,
                "name" => "8 Songs + Dolby Atmos",
                "image" => "service-images/10.jpg",
                "price" => 1800,
                "discounted_price" => 1500,
                "service_type" => "one_time",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mastering Services, Single Deal",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 3,
                "label_id" => 1,
                "name" => "5 Songs",
                "image" => "service-images/11.jpg",
                "price" => 500,
                "discounted_price" => null,
                "service_type" => "subscription",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mastering Services, Monthly Package",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 3,
                "label_id" => 1,
                "name" => "10 Songs",
                "image" => "service-images/12.jpg",
                "price" => 1000,
                "discounted_price" => null,
                "service_type" => "subscription",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mastering Services, Monthly Package",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 4,
                "label_id" => 1,
                "name" => "1 Song",
                "image" => "service-images/13.jpg",
                "price" => 150,
                "discounted_price" => null,
                "service_type" => "one_time",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mixing & Mastering, Single Deal",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 4,
                "label_id" => 1,
                "name" => "1 Song + Dolby Atmos",
                "image" => "service-images/14.jpg",
                "price" => 299,
                "discounted_price" => null,
                "service_type" => "one_time",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mixing & Mastering, Single Deal",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 4,
                "label_id" => 1,
                "name" => "8 Songs",
                "image" => "service-images/15.jpg",
                "price" => 1199,
                "discounted_price" => 999,
                "service_type" => "one_time",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mixing & Mastering, Single Deal",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 4,
                "label_id" => 1,
                "name" => "8 Songs + Dolby Atmos",
                "image" => "service-images/16.jpg",
                "price" => 2399,
                "discounted_price" => 1999,
                "service_type" => "one_time",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mixing & Mastering, Single Deal",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 4,
                "label_id" => 1,
                "name" => "5 Songs",
                "image" => "service-images/17.jpg",
                "price" => 599,
                "discounted_price" => null,
                "service_type" => "subscription",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mixing & Mastering, Monthly Package",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "category_id" => 4,
                "label_id" => 1,
                "name" => "10 Songs",
                "image" => "service-images/18.jpg",
                "price" => 1200,
                "discounted_price" => null,
                "service_type" => "subscription",
                "detail" => "details is here...",
                "brief_detail" => "",
                "includes" => "",
                "description" => "",
                "requirements" => "",
                "notes" => "",
                "tags" => "Mixing & Mastering, Monthly Package",
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ]);
    }
}
