name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Change to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Debug secrets
        run: echo "Deploying to: ${{ secrets.USERNAME }}@${{ secrets.HOST }}"

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
            cd /var/www/back.audiomixingmastering.com
            git pull origin main
            npm install
            pm2 restart audio-mixing-and-mastering-backend
          EOF
